[package]
name = "sproc"
version = "0.1.0"
edition = "2021"
authors = ["hkau"]
description = "Simple service management"
homepage = "https://github.com/hkauso/sproc"
repository = "https://github.com/hkauso/sproc"
license = "MIT"

[dependencies]
clap = { version = "4.5.8", features = ["derive"] }
serde = { version = "1.0.203", features = ["derive"] }
sysinfo = "0.30.12"
toml = "0.8.14"

[[bin]]
path = "src/main.rs"
name = "sproc"
test = false
